00:51:00:692  WARN 33836 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=17m14s533ms326µs300ns).
01:58:50:184  WARN 33836 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1h1m49s337ms616µs500ns).
02:10:51:509  INFO 14364 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 14364 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
02:10:51:510 DEBUG 14364 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
02:10:51:510  INFO 14364 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
02:10:52:296  INFO 14364 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
02:10:52:298  INFO 14364 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
02:10:52:325  INFO 14364 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 Redis repository interfaces.
02:10:54:089  WARN 14364 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
02:10:54:881  INFO 14364 --- [main] org.redisson.Version                     : Redisson 3.17.1
02:10:55:062  INFO 14364 --- [redisson-netty-6-9] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
02:10:55:108  INFO 14364 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
02:10:56:339  INFO 14364 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
02:10:56:615  INFO 14364 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
02:10:56:872  INFO 14364 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
02:10:56:876  INFO 14364 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
02:10:56:925  INFO 14364 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
02:10:57:088  WARN 14364 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
02:10:57:141  INFO 14364 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.912 seconds (JVM running for 7.072)
02:10:57:143  INFO 14364 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
02:10:57:417  INFO 14364 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
02:10:57:622  INFO 14364 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
02:10:58:049  INFO 14364 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
02:10:58:061  INFO 14364 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
02:24:00:215  INFO 32432 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 32432 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
02:24:00:216 DEBUG 32432 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
02:24:00:217  INFO 32432 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
02:24:00:981  INFO 32432 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
02:24:00:983  INFO 32432 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
02:24:01:007  INFO 32432 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
02:24:02:637  WARN 32432 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
02:24:03:534  INFO 32432 --- [main] org.redisson.Version                     : Redisson 3.17.1
02:24:03:732  INFO 32432 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
02:24:03:781  INFO 32432 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
02:24:05:068  INFO 32432 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
02:24:05:345  INFO 32432 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
02:24:05:653  INFO 32432 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
02:24:05:656  INFO 32432 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
02:24:05:686  INFO 32432 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
02:24:05:817  WARN 32432 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
02:24:05:870  INFO 32432 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.942 seconds (JVM running for 6.864)
02:24:05:872  INFO 32432 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
02:24:06:086  INFO 32432 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
02:24:06:261  INFO 32432 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
02:24:06:651  INFO 32432 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
02:24:06:664  INFO 32432 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
02:30:27:001  INFO 27376 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 27376 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
02:30:27:002 DEBUG 27376 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
02:30:27:003  INFO 27376 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
02:30:27:765  INFO 27376 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
02:30:27:768  INFO 27376 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
02:30:27:793  INFO 27376 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
02:30:29:391  WARN 27376 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
02:30:30:199  INFO 27376 --- [main] org.redisson.Version                     : Redisson 3.17.1
02:30:30:385  INFO 27376 --- [redisson-netty-6-8] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
02:30:30:432  INFO 27376 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
02:30:31:628  INFO 27376 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
02:30:31:872  INFO 27376 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
02:30:32:127  INFO 27376 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
02:30:32:131  INFO 27376 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
02:30:32:160  INFO 27376 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
02:30:32:298  WARN 27376 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
02:30:32:355  INFO 27376 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.712 seconds (JVM running for 6.836)
02:30:32:357  INFO 27376 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
02:30:32:577  INFO 27376 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
02:30:32:750  INFO 27376 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
02:30:33:130  INFO 27376 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
02:30:33:142  INFO 27376 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
02:44:20:702  INFO 31392 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 31392 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
02:44:20:704 DEBUG 31392 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
02:44:20:704  INFO 31392 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
02:44:21:474  INFO 31392 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
02:44:21:476  INFO 31392 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
02:44:21:501  INFO 31392 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
02:44:23:100  WARN 31392 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
02:44:23:935  INFO 31392 --- [main] org.redisson.Version                     : Redisson 3.17.1
02:44:24:128  INFO 31392 --- [redisson-netty-6-8] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
02:44:24:174  INFO 31392 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
02:44:25:448  INFO 31392 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
02:44:25:717  INFO 31392 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
02:44:26:026  INFO 31392 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
02:44:26:030  INFO 31392 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
02:44:26:063  INFO 31392 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
02:44:26:186  WARN 31392 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
02:44:26:248  INFO 31392 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.849 seconds (JVM running for 6.809)
02:44:26:250  INFO 31392 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
02:44:26:499  INFO 31392 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
02:44:26:686  INFO 31392 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
02:44:27:079  INFO 31392 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
02:44:27:089  INFO 31392 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
02:44:31:016  INFO 36500 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 36500 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
02:44:31:018 DEBUG 36500 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
02:44:31:018  INFO 36500 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
02:44:31:496  INFO 36500 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
02:44:31:497  INFO 36500 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
02:44:31:520  INFO 36500 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14 ms. Found 0 Redis repository interfaces.
02:44:31:838  INFO 36500 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
02:44:31:845  INFO 36500 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
02:44:31:846  INFO 36500 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
02:44:31:935  INFO 36500 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
02:44:31:935  INFO 36500 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 895 ms
02:44:32:569  WARN 36500 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
02:44:33:044  INFO 36500 --- [main] org.redisson.Version                     : Redisson 3.17.1
02:44:33:184  INFO 36500 --- [redisson-netty-6-18] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
02:44:33:215  INFO 36500 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
02:44:33:557  INFO 36500 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
02:44:33:606  INFO 36500 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
02:44:33:736  INFO 36500 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
02:44:33:737  INFO 36500 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
02:44:33:738  INFO 36500 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
02:44:33:756  INFO 36500 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
02:44:33:828  WARN 36500 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
02:44:33:856  INFO 36500 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 3.079 seconds (JVM running for 3.933)
02:44:33:859  INFO 36500 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
02:44:33:993  INFO 36500 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
02:44:34:130  INFO 36500 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
02:44:34:140  INFO 36500 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
02:44:48:660  INFO 36500 --- [http-nio-8000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
02:44:48:660  INFO 36500 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
02:44:48:662  INFO 36500 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
02:44:49:139 ERROR 36500 --- [http-nio-8000-exec-2] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
02:44:51:406 ERROR 36500 --- [http-nio-8000-exec-5] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
02:45:13:435 ERROR 36500 --- [http-nio-8000-exec-6] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
02:46:37:492 ERROR 36500 --- [http-nio-8000-exec-9] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
02:46:38:990 ERROR 36500 --- [http-nio-8000-exec-10] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
02:46:45:930 ERROR 36500 --- [http-nio-8000-exec-1] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
02:46:48:055 DEBUG 36500 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
02:46:48:089 DEBUG 36500 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
02:46:48:136 DEBUG 36500 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
02:46:48:150 ERROR 36500 --- [http-nio-8000-exec-3] c.q.c.exception.GlobalExceptionHandler   : 请求地址:/api/user/continueDays错误
03:00:22:263  INFO 21344 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 21344 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:00:22:264 DEBUG 21344 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
03:00:22:265  INFO 21344 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
03:00:22:730  INFO 21344 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:00:22:731  INFO 21344 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:00:22:754  INFO 21344 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
03:00:23:087  INFO 21344 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
03:00:23:092  INFO 21344 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
03:00:23:092  INFO 21344 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
03:00:23:174  INFO 21344 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
03:00:23:174  INFO 21344 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 887 ms
03:00:23:761  WARN 21344 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:00:24:230  INFO 21344 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:00:24:346  INFO 21344 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:00:24:376  INFO 21344 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:00:24:704  INFO 21344 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:00:24:754  INFO 21344 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:00:24:870  INFO 21344 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
03:00:24:872  INFO 21344 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:00:24:873  INFO 21344 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:00:24:890  INFO 21344 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:00:24:966  WARN 21344 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:00:24:993  INFO 21344 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 2.966 seconds (JVM running for 3.627)
03:00:24:995  INFO 21344 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:00:25:136  INFO 21344 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:00:25:273  INFO 21344 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:00:25:279  INFO 21344 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
03:00:34:808  INFO 21344 --- [http-nio-8000-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
03:00:34:809  INFO 21344 --- [http-nio-8000-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
03:00:34:811  INFO 21344 --- [http-nio-8000-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
03:00:34:998 DEBUG 21344 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:00:35:033 DEBUG 21344 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:00:35:076 DEBUG 21344 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:01:07:134 ERROR 21344 --- [http-nio-8000-exec-2] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:01:32:668  INFO 30764 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 30764 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:01:32:669 DEBUG 30764 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
03:01:32:670  INFO 30764 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
03:01:33:172  INFO 30764 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:01:33:173  INFO 30764 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:01:33:195  INFO 30764 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14 ms. Found 0 Redis repository interfaces.
03:01:33:521  INFO 30764 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
03:01:33:526  INFO 30764 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
03:01:33:526  INFO 30764 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
03:01:33:613  INFO 30764 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
03:01:33:613  INFO 30764 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 918 ms
03:01:34:232  WARN 30764 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:01:34:745  INFO 30764 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:01:34:855  INFO 30764 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:01:34:884  INFO 30764 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:01:35:314  INFO 30764 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:01:35:396  INFO 30764 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:01:35:506  INFO 30764 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
03:01:35:507  INFO 30764 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:01:35:509  INFO 30764 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:01:35:528  INFO 30764 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:01:35:608  WARN 30764 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:01:35:637  INFO 30764 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 3.21 seconds (JVM running for 4.059)
03:01:35:639  INFO 30764 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:01:35:786  INFO 30764 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:01:35:931  INFO 30764 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:01:35:938  INFO 30764 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
03:01:43:885  INFO 30764 --- [http-nio-8000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
03:01:43:886  INFO 30764 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
03:01:43:889  INFO 30764 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
03:01:49:699 ERROR 30764 --- [http-nio-8000-exec-2] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:01:51:384 DEBUG 30764 --- [http-nio-8000-exec-4] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:01:51:421 DEBUG 30764 --- [http-nio-8000-exec-4] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:01:51:464 DEBUG 30764 --- [http-nio-8000-exec-4] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:01:58:969 DEBUG 30764 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:01:58:970 DEBUG 30764 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:01:58:972 DEBUG 30764 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:02:19:613 DEBUG 30764 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:02:19:614 DEBUG 30764 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:02:19:616 DEBUG 30764 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:07:28:292  WARN 30764 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=5m15s518ms309µs899ns).
03:07:28:518  INFO 30764 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
03:07:28:527  INFO 30764 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
03:07:33:629  INFO 15000 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 15000 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:07:33:630 DEBUG 15000 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
03:07:33:630  INFO 15000 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
03:07:34:105  INFO 15000 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:07:34:106  INFO 15000 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:07:34:129  INFO 15000 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 15 ms. Found 0 Redis repository interfaces.
03:07:34:443  INFO 15000 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
03:07:34:448  INFO 15000 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
03:07:34:449  INFO 15000 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
03:07:34:529  INFO 15000 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
03:07:34:529  INFO 15000 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 875 ms
03:07:35:102  WARN 15000 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:07:35:566  INFO 15000 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:07:35:659  INFO 15000 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:07:35:683  INFO 15000 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:07:36:009  INFO 15000 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:07:36:059  INFO 15000 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:07:36:173  INFO 15000 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
03:07:36:174  INFO 15000 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:07:36:175  INFO 15000 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:07:36:191  INFO 15000 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:07:36:263  WARN 15000 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:07:36:288  INFO 15000 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 2.901 seconds (JVM running for 3.573)
03:07:36:290  INFO 15000 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:07:36:429  INFO 15000 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:07:36:561  INFO 15000 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:07:36:566  INFO 15000 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
03:07:40:023  INFO 15000 --- [http-nio-8000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
03:07:40:024  INFO 15000 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
03:07:40:025  INFO 15000 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
03:07:40:090 DEBUG 15000 --- [http-nio-8000-exec-1] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:07:40:102 DEBUG 15000 --- [http-nio-8000-exec-1] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:07:40:117 DEBUG 15000 --- [http-nio-8000-exec-1] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:08:40:954  INFO 25664 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 25664 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:08:40:955 DEBUG 25664 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
03:08:40:956  INFO 25664 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
03:08:41:430  INFO 25664 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:08:41:431  INFO 25664 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:08:41:453  INFO 25664 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14 ms. Found 0 Redis repository interfaces.
03:08:41:747  INFO 25664 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
03:08:41:753  INFO 25664 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
03:08:41:753  INFO 25664 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
03:08:41:835  INFO 25664 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
03:08:41:836  INFO 25664 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 856 ms
03:08:42:412  WARN 25664 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:08:42:893  INFO 25664 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:08:42:996  INFO 25664 --- [redisson-netty-6-11] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:08:43:024  INFO 25664 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:08:43:343  INFO 25664 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:08:43:393  INFO 25664 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:08:43:512  INFO 25664 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
03:08:43:513  INFO 25664 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:08:43:513  INFO 25664 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:08:43:529  INFO 25664 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:08:43:606  WARN 25664 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:08:43:632  INFO 25664 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 2.912 seconds (JVM running for 3.751)
03:08:43:634  INFO 25664 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:08:43:774  INFO 25664 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:08:43:923  INFO 25664 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:08:43:930  INFO 25664 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
03:08:48:259  INFO 25664 --- [http-nio-8000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
03:08:48:259  INFO 25664 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
03:08:48:260  INFO 25664 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
03:08:48:280 ERROR 25664 --- [http-nio-8000-exec-1] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:08:56:861 ERROR 25664 --- [http-nio-8000-exec-4] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:08:58:095 DEBUG 25664 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:08:58:127 DEBUG 25664 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:08:58:173 DEBUG 25664 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:11:53:742  INFO 35348 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 35348 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:11:53:743 DEBUG 35348 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
03:11:53:743  INFO 35348 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
03:11:54:512  INFO 35348 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:11:54:514  INFO 35348 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:11:54:539  INFO 35348 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
03:11:56:144  WARN 35348 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:11:56:953  INFO 35348 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:11:57:125  INFO 35348 --- [redisson-netty-6-8] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:11:57:171  INFO 35348 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:11:58:514  INFO 35348 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:11:58:784  INFO 35348 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:11:59:080  INFO 35348 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:11:59:085  INFO 35348 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:11:59:129  INFO 35348 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:11:59:257  WARN 35348 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:11:59:318  INFO 35348 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.871 seconds (JVM running for 6.788)
03:11:59:319  INFO 35348 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:11:59:559  INFO 35348 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:11:59:731  INFO 35348 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:12:00:158  INFO 35348 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
03:12:00:176  INFO 35348 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
03:13:07:171 ERROR 25664 --- [http-nio-8000-exec-2] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:13:31:554  INFO 36788 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 36788 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:13:31:555 DEBUG 36788 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
03:13:31:555  INFO 36788 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
03:13:32:312  INFO 36788 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:13:32:313  INFO 36788 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:13:32:338  INFO 36788 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
03:13:33:951  WARN 36788 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:13:34:753  INFO 36788 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:13:34:914  INFO 36788 --- [redisson-netty-6-8] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:13:34:952  INFO 36788 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:13:36:180  INFO 36788 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:13:36:454  INFO 36788 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:13:36:778  INFO 36788 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:13:36:783  INFO 36788 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:13:36:821  INFO 36788 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:13:36:958  WARN 36788 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:13:37:009  INFO 36788 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.752 seconds (JVM running for 6.647)
03:13:37:012  INFO 36788 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:13:37:224  INFO 36788 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:13:37:399  INFO 36788 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:13:37:780  INFO 36788 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
03:13:37:793  INFO 36788 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
03:13:45:885 ERROR 25664 --- [http-nio-8000-exec-8] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:13:46:920 DEBUG 25664 --- [http-nio-8000-exec-9] c.qyp.chat.mapper.UserMapper.selectById  : ==>  Preparing: SELECT user_id,email,nick_name,join_type,sex,password,personal_signature,status,create_time,last_login_time,area_name,area_code,last_off_time,coins FROM user WHERE user_id=?
03:13:46:921 DEBUG 25664 --- [http-nio-8000-exec-9] c.qyp.chat.mapper.UserMapper.selectById  : ==> Parameters: Udkq7qzrl98r(String)
03:13:46:922 DEBUG 25664 --- [http-nio-8000-exec-9] c.qyp.chat.mapper.UserMapper.selectById  : <==      Total: 1
03:20:08:741  INFO 14800 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 14800 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:20:08:742 DEBUG 14800 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
03:20:08:742  INFO 14800 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
03:20:09:524  INFO 14800 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:20:09:527  INFO 14800 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:20:09:557  INFO 14800 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
03:20:11:135  WARN 14800 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:20:11:956  INFO 14800 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:20:12:144  INFO 14800 --- [redisson-netty-6-8] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:20:12:189  INFO 14800 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:20:13:597  INFO 14800 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:20:13:931  INFO 14800 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:20:14:216  INFO 14800 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:20:14:221  INFO 14800 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:20:14:267  INFO 14800 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:20:14:409  WARN 14800 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:20:14:460  INFO 14800 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 6.001 seconds (JVM running for 7.016)
03:20:14:462  INFO 14800 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:20:14:718  INFO 14800 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:20:14:958  INFO 14800 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:20:15:376  INFO 14800 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
03:20:15:388  INFO 14800 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
03:20:15:466 ERROR 25664 --- [http-nio-8000-exec-1] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
03:20:42:447  INFO 35912 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 35912 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
03:20:42:449 DEBUG 35912 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
03:20:42:449  INFO 35912 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
03:20:42:925  INFO 35912 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
03:20:42:926  INFO 35912 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
03:20:42:949  INFO 35912 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14 ms. Found 0 Redis repository interfaces.
03:20:43:250  INFO 35912 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
03:20:43:256  INFO 35912 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
03:20:43:256  INFO 35912 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
03:20:43:339  INFO 35912 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
03:20:43:339  INFO 35912 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 865 ms
03:20:43:927  WARN 35912 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
03:20:44:397  INFO 35912 --- [main] org.redisson.Version                     : Redisson 3.17.1
03:20:44:513  INFO 35912 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
03:20:44:539  INFO 35912 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
03:20:44:859  INFO 35912 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
03:20:44:907  INFO 35912 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
03:20:45:031  INFO 35912 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
03:20:45:031  INFO 35912 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
03:20:45:033  INFO 35912 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
03:20:45:049  INFO 35912 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
03:20:45:124  WARN 35912 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
03:20:45:150  INFO 35912 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 2.944 seconds (JVM running for 3.662)
03:20:45:151  INFO 35912 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
03:20:45:286  INFO 35912 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
03:20:45:419  INFO 35912 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
03:20:45:425  INFO 35912 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
03:20:49:719  INFO 35912 --- [http-nio-8000-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
03:20:49:720  INFO 35912 --- [http-nio-8000-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
03:20:49:721  INFO 35912 --- [http-nio-8000-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
03:20:49:773 ERROR 35912 --- [http-nio-8000-exec-3] c.q.c.exception.GlobalExceptionHandler   : 请求地址:/api/user/sign错误
03:37:13:071  WARN 35912 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=3m57s494ms914µs199ns).
11:30:57:764  WARN 35912 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=7h46m44s561ms996µs).
18:04:31:543 ERROR 35912 --- [redisson-netty-6-24] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x5f4a75ae, L:/192.168.15.1:52746 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-28] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x82bfb926, L:/192.168.15.1:52747 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-3] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x7fa5ee40, L:/192.168.15.1:52736 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-4] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xbbf7ee1f, L:/192.168.15.1:52735 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-15] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x43ff05ea, L:/192.168.15.1:52742 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-11] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xb53bdd92, L:/192.168.15.1:52753 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-2] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xb9f34f73, L:/192.168.15.1:52733 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-18] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xd851a1f6, L:/192.168.15.1:52738 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-7] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x73de993c, L:/192.168.15.1:52734 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-13] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xf7623f14, L:/192.168.15.1:52755 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-22] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xbc815961, L:/192.168.15.1:52743 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543  INFO 35912 --- [lettuce-nioEventLoop-9-1] io.lettuce.core.protocol.CommandHandler  : null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-12] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x3303f5ba, L:/192.168.15.1:52756 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-25] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xc8003525, L:/192.168.15.1:52744 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-32] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x3e60f73d, L:/192.168.15.1:52751 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-6] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xf6d05572, L:/192.168.15.1:52737 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-26] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xc35d77c2, L:/192.168.15.1:52745 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-16] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xc0d5a888, L:/192.168.15.1:52740 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-17] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x9ad68651, L:/192.168.15.1:52739 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-30] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x055ebbc2, L:/192.168.15.1:52748 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-5] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x3c1aafe8, L:/192.168.15.1:52732 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:543 ERROR 35912 --- [redisson-netty-6-14] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x61a67826, L:/192.168.15.1:52754 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:556 ERROR 35912 --- [redisson-netty-6-6] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xa6e15d12, L:/192.168.15.1:52752 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:556 ERROR 35912 --- [redisson-netty-6-14] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xbc910e1e, L:/192.168.15.1:52741 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:556 ERROR 35912 --- [redisson-netty-6-4] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xef404384, L:/192.168.15.1:52749 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:581 ERROR 35912 --- [redisson-netty-6-3] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x7803b839, L:/192.168.15.1:52750 - R:192.168.15.155/192.168.15.155:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:821) ~[netty-buffer-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:04:31:699  INFO 35912 --- [lettuce-eventExecutorLoop-4-4] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /192.168.15.155:6379
18:04:31:732  WARN 35912 --- [lettuce-nioEventLoop-9-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [192.168.15.155:6379]: Network is unreachable: no further information: /192.168.15.155:6379

io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /192.168.15.155:6379
Caused by: java.net.SocketException: Network is unreachable: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:52:01:900  INFO 35912 --- [lettuce-eventExecutorLoop-4-8] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 192.168.15.155:6379
18:52:02:021  WARN 35912 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=6h23m41s696ms82µs100ns).
18:52:02:133  WARN 35912 --- [lettuce-nioEventLoop-9-6] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [192.168.15.155:6379]: No route to host: no further information: /192.168.15.155:6379

io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /192.168.15.155:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

18:52:14:567  INFO 35912 --- [lettuce-eventExecutorLoop-4-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 192.168.15.155:6379
18:52:14:576  INFO 35912 --- [lettuce-nioEventLoop-9-11] i.l.core.protocol.ReconnectionHandler    : Reconnected to 192.168.15.155:6379
19:04:16:930 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x44681023, L:/192.168.15.1:53332 ! R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:032 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x4426ac31, L:/192.168.15.1:53334 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:033 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x96c73767, L:/192.168.15.1:53335 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:034 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xa71bbc70, L:/192.168.15.1:53336 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:236 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xe58bca54, L:/192.168.15.1:53337 ! R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:236 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x0c3d3b2a, L:/192.168.15.1:53338 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:237 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xf9fc436a, L:/192.168.15.1:53339 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:327 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x6a4883bc, L:/192.168.15.1:53346 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:328 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xf1641777, L:/192.168.15.1:53340 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:329 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x386ccafa, L:/192.168.15.1:53341 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:331 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x38e3e86a, L:/192.168.15.1:53345 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:331 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x8c9e5ca5, L:/192.168.15.1:53344 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:332 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x7fa365b4, L:/192.168.15.1:53351 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:333 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x3050e20c, L:/192.168.15.1:53348 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:333 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xf5b3ab18, L:/192.168.15.1:53347 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:334 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x6e0cd79c, L:/192.168.15.1:53350 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:335 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xc9aa1f8b, L:/192.168.15.1:53352 ! R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:335 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x176548df, L:/192.168.15.1:53349 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:336 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x5320081e, L:/192.168.15.1:53354 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:17:340 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x82e90a1e, L:/192.168.15.1:53353 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:18:530 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xa9e18297, L:/192.168.15.1:53377 ! R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:18:731 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xaa008985, L:/192.168.15.1:53380 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:18:732 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x37b05ddf, L:/192.168.15.1:53381 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:18:932 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x6c3650b3, L:/192.168.15.1:53386 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

19:04:18:932 ERROR 35912 --- [redisson-timer-8-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xc8ee6210, L:/192.168.15.1:53385 - R:192.168.15.155/192.168.15.155:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.15.155:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.1.jar:3.17.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

21:11:38:486  INFO 31856 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 31856 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
21:11:38:488 DEBUG 31856 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
21:11:38:489  INFO 31856 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
21:11:39:100  INFO 31856 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
21:11:39:102  INFO 31856 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
21:11:39:130  INFO 31856 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 Redis repository interfaces.
21:11:39:524  INFO 31856 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
21:11:39:532  INFO 31856 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
21:11:39:532  INFO 31856 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
21:11:39:816  INFO 31856 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
21:11:39:817  INFO 31856 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1291 ms
21:11:40:563  WARN 31856 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
21:11:41:126  INFO 31856 --- [main] org.redisson.Version                     : Redisson 3.17.1
21:11:41:403  INFO 31856 --- [redisson-netty-6-20] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
21:11:42:907  INFO 31856 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
21:11:43:274  INFO 31856 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
21:11:43:336  INFO 31856 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
21:11:43:476  INFO 31856 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
21:11:43:476  INFO 31856 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
21:11:43:477  INFO 31856 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
21:11:43:496  INFO 31856 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
21:11:43:587  WARN 31856 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
21:11:43:614  INFO 31856 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 5.443 seconds (JVM running for 6.253)
21:11:43:617  INFO 31856 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
21:11:43:824  INFO 31856 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
21:11:43:996  INFO 31856 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
21:11:44:003  INFO 31856 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
21:11:58:697  INFO 31856 --- [http-nio-8000-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
21:11:58:697  INFO 31856 --- [http-nio-8000-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
21:11:58:699  INFO 31856 --- [http-nio-8000-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
21:11:59:143 ERROR 31856 --- [http-nio-8000-exec-5] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:12:02:361 ERROR 31856 --- [http-nio-8000-exec-6] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:12:03:526 ERROR 31856 --- [http-nio-8000-exec-8] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:12:19:844 ERROR 31856 --- [http-nio-8000-exec-1] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:12:21:694 ERROR 31856 --- [http-nio-8000-exec-10] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:12:25:179 ERROR 31856 --- [http-nio-8000-exec-4] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:13:22:330  INFO 23136 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 23136 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
21:13:22:332 DEBUG 23136 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
21:13:22:333  INFO 23136 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
21:13:22:846  INFO 23136 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
21:13:22:847  INFO 23136 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
21:13:22:872  INFO 23136 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16 ms. Found 0 Redis repository interfaces.
21:13:23:219  INFO 23136 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
21:13:23:225  INFO 23136 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
21:13:23:226  INFO 23136 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
21:13:23:317  INFO 23136 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
21:13:23:317  INFO 23136 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 955 ms
21:13:23:935  WARN 23136 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
21:13:24:449  INFO 23136 --- [main] org.redisson.Version                     : Redisson 3.17.1
21:13:24:547  INFO 23136 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
21:13:24:574  INFO 23136 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
21:13:24:940  INFO 23136 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
21:13:24:992  INFO 23136 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
21:13:25:121  INFO 23136 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
21:13:25:122  INFO 23136 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
21:13:25:124  INFO 23136 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
21:13:25:142  INFO 23136 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
21:13:25:226  WARN 23136 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
21:13:25:253  INFO 23136 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 3.182 seconds (JVM running for 3.903)
21:13:25:255  INFO 23136 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
21:13:25:397  INFO 23136 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
21:13:25:540  INFO 23136 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
21:13:25:546  INFO 23136 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
21:13:29:599  INFO 23136 --- [http-nio-8000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
21:13:29:599  INFO 23136 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
21:13:29:600  INFO 23136 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
21:13:29:975 ERROR 23136 --- [http-nio-8000-exec-2] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:14:36:507  INFO 10300 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 10300 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
21:14:36:509 DEBUG 10300 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
21:14:36:509  INFO 10300 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
21:14:37:286  INFO 10300 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
21:14:37:289  INFO 10300 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
21:14:37:323  INFO 10300 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 Redis repository interfaces.
21:14:39:043  WARN 10300 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
21:14:39:775  INFO 10300 --- [main] org.redisson.Version                     : Redisson 3.17.1
21:14:39:965  INFO 10300 --- [redisson-netty-6-8] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
21:14:40:006  INFO 10300 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
21:14:40:883  INFO 10300 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
21:14:41:044  INFO 10300 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
21:14:41:252  INFO 10300 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
21:14:41:254  INFO 10300 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
21:14:41:280  INFO 10300 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
21:14:41:416  WARN 10300 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
21:14:41:474  INFO 10300 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 5.27 seconds (JVM running for 6.265)
21:14:41:476  INFO 10300 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
21:14:41:737  INFO 10300 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
21:14:41:930  INFO 10300 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
21:14:42:332  INFO 10300 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
21:14:42:345  INFO 10300 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
21:15:59:152  INFO 19864 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 19864 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
21:15:59:153 DEBUG 19864 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
21:15:59:154  INFO 19864 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
21:15:59:998  INFO 19864 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
21:16:00:000  INFO 19864 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
21:16:00:034  INFO 19864 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 Redis repository interfaces.
21:16:02:051  WARN 19864 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
21:16:03:010  INFO 19864 --- [main] org.redisson.Version                     : Redisson 3.17.1
21:16:03:201  INFO 19864 --- [redisson-netty-6-10] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
21:16:03:247  INFO 19864 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
21:16:04:250  INFO 19864 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
21:16:04:443  INFO 19864 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
21:16:04:698  INFO 19864 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
21:16:04:700  INFO 19864 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
21:16:04:732  INFO 19864 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
21:16:04:863  WARN 19864 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
21:16:04:913  INFO 19864 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 6.082 seconds (JVM running for 7.074)
21:16:04:915  INFO 19864 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
21:16:05:189  INFO 19864 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
21:16:05:417  INFO 19864 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
21:16:05:829  INFO 19864 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
21:16:05:846  INFO 19864 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
21:16:54:488  INFO 21040 --- [main] com.qyp.chat.ChatApplication             : Starting ChatApplication using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 21040 (D:\Users\qyp\Documents\ideaProjects\Chat\target\classes started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
21:16:54:489 DEBUG 21040 --- [main] com.qyp.chat.ChatApplication             : Running with Spring Boot v2.7.12, Spring v5.3.27
21:16:54:489  INFO 21040 --- [main] com.qyp.chat.ChatApplication             : The following 1 profile is active: "dev"
21:16:55:067  INFO 21040 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
21:16:55:069  INFO 21040 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
21:16:55:094  INFO 21040 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 18 ms. Found 0 Redis repository interfaces.
21:16:55:449  INFO 21040 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
21:16:55:455  INFO 21040 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
21:16:55:456  INFO 21040 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
21:16:55:553  INFO 21040 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
21:16:55:553  INFO 21040 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1034 ms
21:16:56:175  WARN 21040 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
21:16:56:701  INFO 21040 --- [main] org.redisson.Version                     : Redisson 3.17.1
21:16:56:814  INFO 21040 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
21:16:56:842  INFO 21040 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
21:16:57:190  INFO 21040 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
21:16:57:244  INFO 21040 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
21:16:57:368  INFO 21040 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/api'
21:16:57:369  INFO 21040 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
21:16:57:370  INFO 21040 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
21:16:57:387  INFO 21040 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
21:16:57:470  WARN 21040 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
21:16:57:499  INFO 21040 --- [main] com.qyp.chat.ChatApplication             : Started ChatApplication in 3.286 seconds (JVM running for 4.104)
21:16:57:500  INFO 21040 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
21:16:57:651  INFO 21040 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
21:16:57:800  INFO 21040 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
21:16:57:805  INFO 21040 --- [Thread-2] c.q.c.w.netty.NettyWebSocketStarter      : netty启动
21:18:35:632  INFO 21040 --- [http-nio-8000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring DispatcherServlet 'dispatcherServlet'
21:18:35:633  INFO 21040 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
21:18:35:634  INFO 21040 --- [http-nio-8000-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
21:18:35:785 DEBUG 21040 --- [http-nio-8000-exec-1] c.q.c.mapper.CouponsMapper.updateById    : ==>  Preparing: UPDATE coupons SET name=?, cost=?, outdate_time=?, count=?, begin_time=?, end_time=? WHERE coupons_id=?
21:18:35:802 DEBUG 21040 --- [http-nio-8000-exec-1] c.q.c.mapper.CouponsMapper.updateById    : ==> Parameters: 五折卷(String), 10(Integer), 1739116800000(Long), 100(Integer), 1738684800000(Long), 1738857600000(Long), 0(Integer)
21:18:35:850 DEBUG 21040 --- [http-nio-8000-exec-1] c.q.c.mapper.CouponsMapper.updateById    : <==    Updates: 0
21:19:30:851 DEBUG 21040 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.CouponsMapper.insert   : ==>  Preparing: INSERT INTO coupons ( name, cost, outdate_time, count, begin_time, end_time ) VALUES ( ?, ?, ?, ?, ?, ? )
21:19:30:852 DEBUG 21040 --- [http-nio-8000-exec-3] c.qyp.chat.mapper.CouponsMapper.insert   : ==> Parameters: 五折卷(String), 10(Integer), 1739116800000(Long), 100(Integer), 1738684800000(Long), 1738857600000(Long)
21:19:30:917 ERROR 21040 --- [http-nio-8000-exec-3] c.q.c.exception.GlobalExceptionHandler   : 请求地址:/api/admin/saveCoupons错误
21:20:47:753 DEBUG 21040 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.CouponsMapper.insert   : ==>  Preparing: INSERT INTO coupons ( name, cost, outdate_time, count, begin_time, end_time ) VALUES ( ?, ?, ?, ?, ?, ? )
21:20:47:754 DEBUG 21040 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.CouponsMapper.insert   : ==> Parameters: 五折卷(String), 10(Integer), 1739116800000(Long), 100(Integer), 1738684800000(Long), 1738857600000(Long)
21:20:47:759 DEBUG 21040 --- [http-nio-8000-exec-5] c.qyp.chat.mapper.CouponsMapper.insert   : <==    Updates: 1
21:21:37:912  INFO 25252 --- [main] com.qyp.chat.MyTest                      : Starting MyTest using Java 11.0.12 on LAPTOP-C6F2EJ6P with PID 25252 (started by qyp in D:\Users\qyp\Documents\ideaProjects\Chat)
21:21:37:913 DEBUG 25252 --- [main] com.qyp.chat.MyTest                      : Running with Spring Boot v2.7.12, Spring v5.3.27
21:21:37:913  INFO 25252 --- [main] com.qyp.chat.MyTest                      : The following 1 profile is active: "dev"
21:21:38:724  INFO 25252 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
21:21:38:727  INFO 25252 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
21:21:38:769  INFO 25252 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 19 ms. Found 0 Redis repository interfaces.
21:21:41:018  WARN 25252 --- [main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "com.qyp.chat.domain.entity.ExchangeCoupons".
21:21:41:996  INFO 25252 --- [main] org.redisson.Version                     : Redisson 3.17.1
21:21:42:169  INFO 25252 --- [redisson-netty-6-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 192.168.15.155/192.168.15.155:6379
21:21:42:210  INFO 25252 --- [redisson-netty-6-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 192.168.15.155/192.168.15.155:6379
21:21:43:080  INFO 25252 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
21:21:43:276  INFO 25252 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
21:21:43:533  INFO 25252 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Documentation plugins bootstrapped
21:21:43:535  INFO 25252 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
21:21:43:561  INFO 25252 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
21:21:43:677  WARN 25252 --- [main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType org.springframework.web.multipart.MultipartFile[]
21:21:43:736  INFO 25252 --- [main] com.qyp.chat.MyTest                      : Started MyTest in 6.144 seconds (JVM running for 7.132)
21:21:43:737  INFO 25252 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
21:21:44:026  INFO 25252 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
21:21:44:216  INFO 25252 --- [main] com.qyp.chat.InitRun                     : 服务启动成功。
21:21:44:609  INFO 25252 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
21:21:44:621  INFO 25252 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
21:22:35:745 ERROR 21040 --- [http-nio-8000-exec-7] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:22:38:636 DEBUG 21040 --- [http-nio-8000-exec-8] c.q.c.m.C.selectPage_mpCount             : ==>  Preparing: SELECT COUNT(*) FROM coupons
21:22:38:637 DEBUG 21040 --- [http-nio-8000-exec-8] c.q.c.m.C.selectPage_mpCount             : ==> Parameters: 
21:22:38:660 DEBUG 21040 --- [http-nio-8000-exec-8] c.q.c.m.C.selectPage_mpCount             : <==      Total: 1
21:22:38:674 DEBUG 21040 --- [http-nio-8000-exec-8] c.q.c.mapper.CouponsMapper.selectPage    : ==>  Preparing: SELECT coupons_id,name,cost,outdate_time,count,begin_time,end_time FROM coupons LIMIT ?
21:22:38:676 DEBUG 21040 --- [http-nio-8000-exec-8] c.q.c.mapper.CouponsMapper.selectPage    : ==> Parameters: 10(Long)
21:22:38:680 DEBUG 21040 --- [http-nio-8000-exec-8] c.q.c.mapper.CouponsMapper.selectPage    : <==      Total: 1
21:23:01:847 ERROR 21040 --- [http-nio-8000-exec-10] c.qyp.chat.interceptor.LoginInterceptor  : /api/error
21:23:18:697 DEBUG 21040 --- [http-nio-8000-exec-1] c.q.c.mapper.CouponsMapper.updateById    : ==>  Preparing: UPDATE coupons SET name=?, cost=?, outdate_time=?, count=?, begin_time=?, end_time=? WHERE coupons_id=?
21:23:18:699 DEBUG 21040 --- [http-nio-8000-exec-1] c.q.c.mapper.CouponsMapper.updateById    : ==> Parameters: 五折卷(String), 20(Integer), 1739116800000(Long), 100(Integer), 1738684800000(Long), 1738857600000(Long), 1(Integer)
21:23:18:703 DEBUG 21040 --- [http-nio-8000-exec-1] c.q.c.mapper.CouponsMapper.updateById    : <==    Updates: 1
23:48:26:036  WARN 21040 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=4m56s198ms164µs500ns).
